version: '3.9'
services:
  db:
    image: postgres
    container_name: petroshield-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: petroshield
    ports:
      - "5433:5432"  # changed host port to 5433 to avoid conflict
    volumes:
      - db_data:/var/lib/postgresql/data

  fuel-theft-service:
    build: ./fuel-theft-service
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/petroshield"
    depends_on:
      - db

  user-management-service:
    build: ./user-management-service
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/petroshield"
    depends_on:
      - db

  vehicle-service:
    build: ./vehicle-service
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/petroshield"
    depends_on:
      - db

  notification-service:
    build: ./notification-service
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/petroshield"
    depends_on:
      - db

  reporting-service:
    build: ./reporting-service
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/petroshield"
    depends_on:
      - db

volumes:
  db_data:


















# version: '3.9'
# services:
#   db:
#     image: postgres
#     container_name: petroshield-db
#     environment:
#       POSTGRES_USER: user
#       POSTGRES_PASSWORD: password
#       POSTGRES_DB: petroshield
#     ports:
#       - "5432:5432"
#     volumes:
#       - db_data:/var/lib/postgresql/data

#   fuel-theft-service:
#     build: ./fuel-theft-service
#     environment:
#       DATABASE_URL: "postgresql://user:password@db:5432/petroshield"
#     depends_on:
#       - db

#   user-management-service:
#     build: ./user-management-service
#     environment:
#       DATABASE_URL: "postgresql://user:password@db:5432/petroshield"
#     depends_on:
#       - db

#   vehicle-service:
#     build: ./vehicle-service
#     environment:
#       DATABASE_URL: "postgresql://user:password@db:5432/petroshield"
#     depends_on:
#       - db

#   notification-service:
#     build: ./notification-service
#     environment:
#       DATABASE_URL: "postgresql://user:password@db:5432/petroshield"
#     depends_on:
#       - db

#   reporting-service:
#     build: ./reporting-service
#     environment:
#       DATABASE_URL: "postgresql://user:password@db:5432/petroshield"
#     depends_on:
#       - db

# volumes:
#   db_data:
